[window]
decorations = "none"
dynamic_padding = true
startup_mode = "Maximized"
# opacity = 0.95
title = "Alacritty"

[general]
import = [
    "~/.config/alacritty/themes/gruvbox_dark.toml"
]

[env]
TERM = "xterm-256color"

[terminal]
shell = { program = "/usr/bin/fish", args = ["-l"] }

[font]
normal.family = "Hack Nerd Font"
size = 12.0

[cursor]
style = "Block"
unfocused_hollow = true

[keyboard]
bindings = [
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },
]