require("htanmo.plugins_config.lualine")
require("htanmo.plugins_config.treesitter")
require("htanmo.plugins_config.completions")
require("htanmo.plugins_config.mason")
require("htanmo.plugins_config.lsp_config")
require("htanmo.plugins_config.rosepine")
require("htanmo.plugins_config.telescope")
